### ISSUE TITLE
Missing files causing buildtime errors

### ISSUE THREAD

**Issue by chlkbumper** [aleene/FoodViewer#527]
Hello, 

After trying different branches (master, PaggingViewController and 1.5_32), none of them could build because of missing files. Could it be a bad merge/commit ? Or am I cloning it wrong ? Every checkout was made in a new empty folder with no .git config.

Either way, here are the files that seem to always be missing :

```
ProductUpdateStatus.swift
KeyboardViewController.swift
LocalizedNutritionalScoreUK.swift
NutritionalScoreFrance.swift
```

**Comment by aleene** [comment]
I think my last commit went wrong, it threw an error. I will re-try.

**Comment by aleene** [comment]
I pushed them one by one to Github.

However NutritionalScoreFrance.swift is a non-existing file.

**Comment by chlkbumper** [comment]
Still not building... Even after pulling and fresh-cloning, I can't seem to find the missing files on your repo, did you `git add` them ? 

Here are the relevant lines from the error I get :

```
<unknown>:0: error: no such file or directory: '/Users/.../Downloads/FoodViewer/FoodViewer/ProductUpdateStatus.swift'
<unknown>:0: error: no such file or directory: '/Users/.../Downloads/FoodViewer/FoodViewer/KeyboardViewController.swift'
<unknown>:0: error: no such file or directory: '/Users/.../Downloads/FoodViewer/FoodViewer/LocalizedNutritionalScoreUK.swift'
<unknown>:0: error: no such file or directory: '/Users/.../Downloads/FoodViewer/FoodViewer/NutritionalScoreFR.swift'
Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

**Comment by aleene** [comment]
I added the files by hand. I do not understand why the push did not work

**Comment by chlkbumper** [comment]
Problem solved ! Thank you very much 👍

**Comment by aleene** [comment]
Great, adding by hand broke my connection with xcode, so I deleted them again and tried a new push.
